name = "Idyoms"
uuid = "320a6c3d-0181-4444-bfa6-2ef27c907b84"
authors = ["Nick Harley <nickharley@protonmail.com>"]
version = "0.1.0"

[deps]
Chakra = "23337c43-347c-4169-b193-f31a84c326bf"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
